/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder_9 (
    input [5:0] alufn,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] sumresult,
    output reg z,
    output reg v,
    output reg n,
    output reg car
  );
  
  
  
  reg [16:0] sum;
  
  reg [16:0] diff;
  
  always @* begin
    
    case (alufn[0+1-:2])
      2'h0: begin
        sum = a + b;
        diff = a - b;
      end
      2'h1: begin
        sum = a - b;
        diff = a - b;
      end
      2'h2: begin
        sum = a * b;
        diff = a - b;
      end
      2'h3: begin
        sum = a - ((a / b) * b);
        diff = a - b;
      end
      default: begin
        sum = a + b;
        diff = a - b;
      end
    endcase
    sumresult = sum[0+15-:16];
    n = diff[15+0-:1];
    v = (a[15+0-:1] & ~b[15+0-:1] & ~diff[15+0-:1]) | (~a[15+0-:1] & b[15+0-:1] & diff[15+0-:1]);
    car = (a[15+0-:1] & b[15+0-:1] & ~sum[15+0-:1]) | (~a[15+0-:1] & ~b[15+0-:1] & sum[15+0-:1]);
    z = (~|diff);
  end
endmodule
