/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu_1 (
    input [5:0] alufn,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] c,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  wire [16-1:0] M_adder1_sumresult;
  wire [1-1:0] M_adder1_z;
  wire [1-1:0] M_adder1_v;
  wire [1-1:0] M_adder1_n;
  wire [1-1:0] M_adder1_car;
  reg [6-1:0] M_adder1_alufn;
  reg [16-1:0] M_adder1_a;
  reg [16-1:0] M_adder1_b;
  adder_9 adder1 (
    .alufn(M_adder1_alufn),
    .a(M_adder1_a),
    .b(M_adder1_b),
    .sumresult(M_adder1_sumresult),
    .z(M_adder1_z),
    .v(M_adder1_v),
    .n(M_adder1_n),
    .car(M_adder1_car)
  );
  
  wire [16-1:0] M_boolean1_c;
  reg [6-1:0] M_boolean1_alufn;
  reg [16-1:0] M_boolean1_a;
  reg [16-1:0] M_boolean1_b;
  boolean_10 boolean1 (
    .alufn(M_boolean1_alufn),
    .a(M_boolean1_a),
    .b(M_boolean1_b),
    .c(M_boolean1_c)
  );
  
  wire [16-1:0] M_compare1_c;
  reg [6-1:0] M_compare1_alufn;
  reg [16-1:0] M_compare1_a;
  reg [16-1:0] M_compare1_b;
  cmp_11 compare1 (
    .alufn(M_compare1_alufn),
    .a(M_compare1_a),
    .b(M_compare1_b),
    .c(M_compare1_c)
  );
  
  wire [16-1:0] M_shifter1_c;
  reg [6-1:0] M_shifter1_alufn;
  reg [16-1:0] M_shifter1_a;
  reg [16-1:0] M_shifter1_b;
  bitshifter_12 shifter1 (
    .alufn(M_shifter1_alufn),
    .a(M_shifter1_a),
    .b(M_shifter1_b),
    .c(M_shifter1_c)
  );
  
  always @* begin
    z = 1'h0;
    v = 1'h0;
    n = 1'h0;
    M_adder1_alufn = alufn;
    M_adder1_a = a;
    M_adder1_b = b;
    M_boolean1_alufn = alufn;
    M_boolean1_a = a;
    M_boolean1_b = b;
    M_compare1_alufn = alufn;
    M_compare1_a = a;
    M_compare1_b = b;
    M_shifter1_alufn = alufn;
    M_shifter1_a = a;
    M_shifter1_b = b;
    
    case (alufn[4+1-:2])
      2'h0: begin
        c = M_adder1_sumresult;
        z = M_adder1_z;
        v = M_adder1_v;
        n = M_adder1_n;
      end
      2'h1: begin
        c = M_boolean1_c;
      end
      2'h2: begin
        c = M_shifter1_c;
      end
      2'h3: begin
        c = M_compare1_c;
      end
      default: begin
        c = 8'h00;
      end
    endcase
  end
endmodule
