/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module boolean_10 (
    input [5:0] alufn,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] c
  );
  
  
  
  always @* begin
    
    case (alufn)
      6'h1e: begin
        c = a | b;
      end
      6'h16: begin
        c = a ^ b;
      end
      6'h18: begin
        c = a & b;
      end
      6'h1a: begin
        c = a;
      end
      default: begin
        c = 1'h0;
      end
    endcase
  end
endmodule
